# Dimensiones de pantalla
WIDTH, HEIGHT = 600, 700
LANE_LEFT_X  = WIDTH // 2 - 110
LANE_RIGHT_X = WIDTH // 2 + 110
PLAYER_Y     = HEIGHT - 180
FPS          = 60

# Tamaños de fuente
FONT_SIZE_BIG = 64
FONT_SIZE_MED = 32
FONT_SIZE_SMALL = 22

# Estado inicial del jugador
INITIAL_LANE = "L"
INITIAL_SCORE = 0
INITIAL_LIVES = 3
INITIAL_LEVEL = 1
INITIAL_COMBO = 0

INITIAL_SPEED = 4.0
INITIAL_SPAWN_INTERVAL = 2.2
MAX_LEVEL = 20
MAX_SPEED = 12.0
MIN_SPAWN_INTERVAL = 1.3

SCORE_GAIN_BASE = 10
SCORE_GAIN_COMBO_MULTIPLIER = 2
SCORE_PENALTY = 5

COMBO_LEVEL_UP_INTERVAL = 3
SPEED_INCREASE = 0.4
SPAWN_INTERVAL_DECREASE = 0.05
